bythemetro/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^login/$', 'django.contrib.auth.views.login'),
    (r'', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('bythemetro.views',
    (r'^$', 'main_page'),
    (r'^map/$', 'map'),
    (r'^table/$', 'table'),

    (r'^user/(?P<user_id>\d+)/$', 'user_page'),
    (r'^alerts/$', 'alerts'),
    (r'^create_alert/$', 'create_alert'),
    (r'^alert/(?P<alert_id>\d+)/$', 'alert_detail'),
    (r'^alert/(?P<alert_id>\d+)/edit/$', 'edit_alert'),
    (r'^alert/(?P<alert_id>\d+)/delete/$', 'delete_alert'),

    (r'^logout/$', 'logout_page'),
    (r'^register/$', 'register_page'),
)

bythemetro/models.py
import re

from django.contrib.auth.models import User
from django.db import models

class MetroSystem(models.Model):
    """
    name - eg, DC Metro, Boston T, Chicago L, ...
    rssfeed - craigslist link to rss feed
    """
    name = models.CharField(max_length=128, unique=True)
    rssfeed = models.URLField(unique=True)

    def __unicode__(self):
        return '%s' % (self.name)

class Station(models.Model):
    system = models.ForeignKey(MetroSystem)
    name = models.CharField(max_length=128, unique=True)
    lat = models.FloatField()
    lng = models.FloatField()

    def __unicode__(self):
        return self.name

class Apartment(models.Model):
    url = models.URLField(unique=True)
    lat = models.FloatField()
    lng = models.FloatField()
    title = models.CharField(max_length=128)
    price = models.IntegerField(null=True)
    num_bedrooms = models.IntegerField(default=False)
    allows_cats = models.BooleanField(default=False)
    allows_dogs = models.BooleanField(default=False)
    has_image = models.BooleanField(default=False)
    date = models.DateTimeField('date last checked')

    def __unicode__(self):
        return '%s [%s]' % (self.title, self.url)

class CheckedLink(models.Model):
    url = models.URLField(unique=True)
    date = models.DateTimeField('date last checked')

    def __unicode__(self):
        return '%s [%s]' % (self.url, self.date)

class ApartmentNearStation(models.Model):
    station = models.ForeignKey(Station)
    distance = models.FloatField()
    apartment = models.ForeignKey(Apartment)

    def __unicode__(self):
        return '%s (%.2f):\t%s' % (self.station, self.distance, self.apartment)

class ApartmentAlert(models.Model):
    user = models.ForeignKey(User)
    station = models.ForeignKey(Station)
    distance = models.IntegerField()
    num_bedrooms = models.IntegerField(null=True, blank=True)
    min_price = models.IntegerField(null=True, blank=True)
    max_price = models.IntegerField(null=True, blank=True)
    allows_cats = models.BooleanField(default=False)
    allows_dogs = models.BooleanField(default=False)
    has_image = models.BooleanField(default=False)

    def __unicode__(self):
        return '%s %d' % (self.station, self.distance)

class AlreadyAlerted(models.Model):
    apartment = models.ForeignKey(Apartment)
    alert = models.ForeignKey(ApartmentAlert)
    user = models.ForeignKey(User)
    date = models.DateTimeField('date alerted')
    

bythemetro/forms.py
import os, re

from django import forms
from django.contrib.auth.models import User
from models import ApartmentAlert

class RegistrationForm(forms.Form):
    username = forms.CharField(label=u'Username', max_length=32)
    email = forms.EmailField(label=u'Email')
    password1 = forms.CharField(
        label=u'Password',
        widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        label=u'Password (again)',
        widget=forms.PasswordInput()
    )

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Username can only contain '
                                        'alphanumeric characters and the underscore')

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise forms.ValidationError('Username is already taken.')

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email

        raise forms.ValidationError('Email address is already registered.')
            
    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:

                return password2
        raise forms.ValidationError('Passwords do not match')
    
class ApartmentAlertForm(forms.ModelForm):
    class Meta:
        model = ApartmentAlert
        exclude = ('user',)

bythemetro/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.template import RequestContext

from bythemetro.models import *
from bythemetro.forms import RegistrationForm, ApartmentAlertForm

def main_page(request):
    metro_system = MetroSystem.objects.get(pk=1)
    vars = RequestContext(request, {'metro_system': metro_system})
    return render_to_response('map.html', vars)

def map(request):
    metro_system = MetroSystem.objects.get(pk=1)
    vars = RequestContext(request, {'metro_system': metro_system})
    return render_to_response('map.html', vars)

def table(request):
    metro_system = MetroSystem.objects.get(pk=1)
    vars = RequestContext(request, {'metro_system': metro_system})
    return render_to_response('table.html', vars)

def logout_page(request):
    logout(request)
    return HttpResponseRedirect('/')

@login_required
def user_page(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    vars = RequestContext(request)
    return render_to_response('user.html', vars)

def alerts(request):
    """
    Display a list of alerts that the user has configured. Or if the
    user has not logged in, then the template will display a message
    indicating that the user must login before configuring any alerts.
    """
    vars = RequestContext(request)
    if request.user.is_authenticated():
        user = get_object_or_404(User, pk=request.user.id)
        vars.update({'alert_list': user.apartmentalert_set.all()})
    return render_to_response('alerts/index.html', vars)
    
@login_required
def alert_detail(request, alert_id):
    alert = get_object_or_404(ApartmentAlert, pk=alert_id)
    vars = RequestContext(request, {'alert': alert})
    return render_to_response('alerts/detail.html', vars)
    
def register_page(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                username = form.cleaned_data['username'],
                password = form.cleaned_data['password1'],
                email = form.cleaned_data['email']
            )
            return HttpResponseRedirect('/')
    else:
        form = RegistrationForm()

    vars = RequestContext(request, {'form': form})
    return render_to_response('registration/register.html', vars)

def create_alert(request):
    if request.method == 'POST':
        form = ApartmentAlertForm(request.POST)
        if form.is_valid():
            alert = form.save(commit=False)
            alert.user = request.user
            alert.save()
            return HttpResponseRedirect('/alerts/')
    else:
        form = ApartmentAlertForm()

    vars = RequestContext(request, {'form': form})
    return render_to_response('alerts/create.html', vars)

def edit_alert(request, alert_id):
    alert = get_object_or_404(ApartmentAlert, pk=alert_id)
        
    if request.method == 'POST':
        form = ApartmentAlertForm(request.POST, instance=alert)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/alerts/')
    else:
        form = ApartmentAlertForm(instance=alert)

    vars = RequestContext(request, {'form': form})
    return render_to_response('alerts/edit.html', vars)

def delete_alert(request, alert_id):
    alert = get_object_or_404(ApartmentAlert, pk=alert_id)
        
    if request.method == 'POST':
        print request.POST
        alert.delete()
        return HttpResponseRedirect('/alerts/')

    vars = RequestContext(request, {'alert': alert})
    return render_to_response('alerts/delete.html', vars)

bythemetro/templates/alerts/create.html
{% extends "base.html" %}

{% block title %} {{ user.username }} {% endblock %}

{% block content %}
<h1> Create Alert </h1>
<form method="post" action=".">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="save" />
</form>
{% endblock %}

bythemetro/templates/alerts/delete.html
{% extends "base.html" %}

{% block title %} {{ user.username }} {% endblock %}
{% block head %}  {% endblock %}

{% block content %}
<h1>Delete Alert</h1>

Are you sure you want to delete the following alert:

{{ alert.station }}

<form method="post" action=".">{% csrf_token %}
  <input type="submit" name="confirm_delete" value="Yes" />
</form>

{% endblock %}

bythemetro/templates/alerts/detail.html
{{ alert }}

bythemetro/templates/alerts/edit.html
{% extends "base.html" %}

{% block title %} {{ user.username }} {% endblock %}
{% block head %} {% endblock %}

{% block content %}
<h1> Edit Alert </h1>
<form method="post" action=".">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="save" />
</form>
{% endblock %}

bythemetro/templates/alerts/index.html
{% extends "base.html" %}

{% block title %}
  {% if user.is_authenticated %}
    {{ user.username }}
  {% else %}
    Register account to create alerts 
  {% endif %}
{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    {% if alert_list %}
      Alerts for {{ user.username }} 
      <table border=1>
        <tr>
          <th>Metro</th>
          <th>Distance (miles)</th>
        </tr>      
        {% for alert in alert_list %}
        <tr>
          <td><a href="/alert/{{ alert.id }}/">{{ alert.station }}</a></td>
          <td>{{ alert.distance }}</td>
          <td>
            <a href="/alert/{{ alert.id }}/edit/">edit</a>
            <a href="/alert/{{ alert.id }}/delete/">delete</a>
          </td>
        </tr>
      {% endfor %}
      </table>
    {% else %}
      <p>You have not created any alerts.</p>
    {% endif %}
    <a href="/create_alert/">Create</a> a new alert.
  {% else %}
    <p>Set up alerts to get notified by email when apartments within walking distance of a metro stop
    become available.</p>
    <p><a href="/login/">Login</a> into your account to create and manage alerts. If you don't already
       have an account, you can register for a new account <a href="/register/">here</a>.</p>
  {% endif %}
{% endblock %}

bythemetro/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title>By the Metro | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/media/style.css" type="text/css" />
    {% block head %}{% endblock %}
  </head>

  <body onload="initialize()">
  <table style="width:100%; height:100%" border=0>
    <tr>
      <td>
        <div id="nav">
          <div style="display: inline; float: left;">
            <a href="/">Map</a>
            | 
            <a href="/alerts">Alerts</a>
          </div>

          <div style="display: inline; float: right;">      
            {% if user.is_authenticated %}
              <a href="/user/{{user.id}}/">{{user.username}}</a> 
              |
            {% else %}
              <a href="/login/">login</a> 
              |
            {% endif %}
              <a href="/help">help</a>
              |
              <a href="/about">about</a>
            {% if user.is_authenticated %}
              |
              <a href="/logout">logout</a>
            {% endif %}
          </div>
        </div>
      </td>
    </tr>
 
    <tr>
      <td><h1>{% block h1 %}{% endblock %}</h1></td>
    </tr>

    <tr style="width:100%; height:100%">
      <td style="width:100%; height:100%">
        {% block content %}{% endblock %}
      </td>
    </tr>
  </table>
  </body>
</html>

bythemetro/templates/main_page.html
{% extends "base.html" %}

{% block title %} Welcome to By the Metro {% endblock %}

{% block content %}
  {% if user.username %}
    <p>Welcome {{ user.username }}! Manage your <a href="/user/{{ user.id }}/">alerts</a></p>
  {% else %}
    <p>You need to <a href="/login/">login</a> before you can create and manage alerts</p>
  {% endif %}

  <br />

  {{ metro_system.name }}
  <ul>
  {% for station in metro_system.station_set.all %}
    <li>{{station.name}}</li>
    <ul>
    {% for apartment_near_station in station.apartmentnearstation_set.all %}
      <li>
        {{apartment_near_station.distance|floatformat}} miles
        <a target='_blank' href='{{apartment_near_station.apartment.url}}'>{{apartment_near_station.apartment.title}}</a>
      </li>
    {% endfor %}
    </ul>
  {% endfor %}
  </ul>
{% endblock %}

bythemetro/templates/map.html
{% extends "base.html" %}

{% block head %}
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; padding: 0 }
      #map_canvas { height: 100% }
    </style>

    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?sensor=false">
    </script>

    <script type="text/javascript">
      var infowindow = null;

      var stations = {};
      var apartments = {};

      {% for station in metro_system.station_set.all %}
        stations['{{station.name}}'] = {
          position: new google.maps.LatLng({{station.lat}}, {{station.lng}})
        };

        {% for apartment_near_station in station.apartmentnearstation_set.all %}
          {% if apartment_near_station.distance <= 0.5 %}
            apartments['{{apartment_near_station.apartment.url}}'] = {
              position: new google.maps.LatLng({{apartment_near_station.apartment.lat}}, {{apartment_near_station.apartment.lng}}),
              desc: "<div class='apartment_desc'>" + 
                    "<a href='{{apartment_near_station.apartment.url}}'>{{apartment_near_station.apartment.title}}</a>" +
                    "<br />{{apartment_near_station.distance|floatformat}} miles from {{apartment_near_station.station.name}} Metro Station" +
                    "</div>"
            };
          {% endif %}
        {% endfor %}
      {% endfor %}
   
      function initialize() {
        var infowindow = new google.maps.InfoWindow({
          content: "temporary"
        });

        var latlng = new google.maps.LatLng(39.085451999999997, -77.146688999999995);

        var myOptions = {
          zoom: 12,
          center: latlng,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

        for (var url in apartments) {
          var markerOptions = {
            position: apartments[url].position,
            html: apartments[url].desc,
            map:map
          };

          marker = new google.maps.Marker(markerOptions);

          google.maps.event.addListener(marker, 'click', function() {
            infowindow.setContent(this.html);
            infowindow.open(map, this);
          });
        }

        var orangeline = new google.maps.Polyline({path:[
          new google.maps.LatLng(38.877693,-77.271562),
          new google.maps.LatLng(38.883015,-77.228939),
          new google.maps.LatLng(38.90067,-77.189394),
          new google.maps.LatLng(38.885841,-77.157177),
          new google.maps.LatLng(38.882071,-77.111845),
          new google.maps.LatLng(38.883104,-77.103177),
          new google.maps.LatLng(38.886373,-77.096963),
          new google.maps.LatLng(38.891499,-77.08391),
          new google.maps.LatLng(38.896595,-77.071460), // Rosslyn
          new google.maps.LatLng(38.900599,-77.050273),
          new google.maps.LatLng(38.901311,-77.03981),
          new google.maps.LatLng(38.901316,-77.033652),
          new google.maps.LatLng(38.898303,-77.028099),
          new google.maps.LatLng(38.893757,-77.028218),
          new google.maps.LatLng(38.888022,-77.028232),
          new google.maps.LatLng(38.884775,-77.021964),
          new google.maps.LatLng(38.884958,-77.01586),
          new google.maps.LatLng(38.884968,-77.005137),
          new google.maps.LatLng(38.884124,-76.995334),
          new google.maps.LatLng(38.880841,-76.985721),
          new google.maps.LatLng(38.88594,-76.977485),
          new google.maps.LatLng(38.898284,-76.948042),
          new google.maps.LatLng(38.907734,-76.936177),
          new google.maps.LatLng(38.91652,-76.915427),
          new google.maps.LatLng(38.934411,-76.890988),
          new google.maps.LatLng(38.947674,-76.872144)], 
          strokeColor:"#FF6600", strokeOpacity:1, strokeWeight:8});
        orangeline.setMap(map);

        // Red line
        var redline = new google.maps.Polyline({path:[
          new google.maps.LatLng(39.119819,-77.164921),
          new google.maps.LatLng(39.084215,-77.146424),
          new google.maps.LatLng(39.062359,-77.121113),
          new google.maps.LatLng(39.048043,-77.113131),
          new google.maps.LatLng(39.029158,-77.10415),
          new google.maps.LatLng(38.999947,-77.097253),
          new google.maps.LatLng(38.984282,-77.094431),
          new google.maps.LatLng(38.960744,-77.085969),
          new google.maps.LatLng(38.947808,-77.079615),
          new google.maps.LatLng(38.94362,-77.063511),
          new google.maps.LatLng(38.934703,-77.058226),
          new google.maps.LatLng(38.924999,-77.052648),
          new google.maps.LatLng(38.909499,-77.04362),
          new google.maps.LatLng(38.903192,-77.039766),
          new google.maps.LatLng(38.898303,-77.028099),
          new google.maps.LatLng(38.89834,-77.021851),
          new google.maps.LatLng(38.896084,-77.016643),
          new google.maps.LatLng(38.897723,-77.006745),
          new google.maps.LatLng(38.910916,-77.00185),
          new google.maps.LatLng(38.920741,-76.995984),
          new google.maps.LatLng(38.933234,-76.994544),
          new google.maps.LatLng(38.951777,-77.002174),
          new google.maps.LatLng(38.975532,-77.017834),
          new google.maps.LatLng(38.993841,-77.031321),
          new google.maps.LatLng(39.015413,-77.042953),
          new google.maps.LatLng(39.038558,-77.051098),
          new google.maps.LatLng(39.061713,-77.05341)], 
          strokeColor:"#ff0033", strokeOpacity:1, strokeWeight:8});
        redline.setMap(map);

        // Green line
        var greenline = new google.maps.Polyline({path:[
          new google.maps.LatLng(38.826995,-76.912134),
          new google.maps.LatLng(38.843891,-76.932022),
          new google.maps.LatLng(38.851187,-76.956565),
          new google.maps.LatLng(38.840974,-76.97536),
          new google.maps.LatLng(38.845334,-76.98817),
          new google.maps.LatLng(38.862072,-76.995648),
          new google.maps.LatLng(38.876588,-77.005086),
          new google.maps.LatLng(38.876221,-77.017491),
          new google.maps.LatLng(38.884775,-77.021964),
          new google.maps.LatLng(38.893893,-77.021902),
          new google.maps.LatLng(38.89834,-77.021851),
          new google.maps.LatLng(38.905604,-77.022256),
          new google.maps.LatLng(38.912919,-77.022194),
          new google.maps.LatLng(38.916489,-77.028938),
          new google.maps.LatLng(38.928672,-77.032775),
          new google.maps.LatLng(38.936077,-77.024728),
          new google.maps.LatLng(38.951777,-77.002174),
          new google.maps.LatLng(38.954931,-76.969881),
          new google.maps.LatLng(38.965276,-76.956182),
          new google.maps.LatLng(38.978523,-76.928432),
          new google.maps.LatLng(39.011036,-76.911362)], 
          strokeColor:"#339933", strokeOpacity:1, strokeWeight:8});
        greenline.setMap(map);

        // Blue line Franconia - Rosslyn
        var blueline_franconia_rosslyn = new google.maps.Polyline({path:[
          new google.maps.LatLng(38.766129,-77.168797),
          new google.maps.LatLng(38.799193,-77.129407),
          new google.maps.LatLng(38.806474,-77.061115),
          new google.maps.LatLng(38.814009,-77.053763),
          new google.maps.LatLng(38.852985,-77.043805),
          new google.maps.LatLng(38.85779,-77.050589),
          new google.maps.LatLng(38.863045,-77.059507),
          new google.maps.LatLng(38.869349,-77.054013),
          new google.maps.LatLng(38.884574,-77.063108),
          new google.maps.LatLng(38.896595,-77.071460)], 
          strokeColor:"#0000CC", strokeOpacity:1, strokeWeight:8}); //Rosslyn
        blueline_franconia_rosslyn.setMap(map);
      
        // Blue line half width Rosslyn - Stadium Armory
        var blueline_rosslyn_armory = new google.maps.Polyline({path:[
          new google.maps.LatLng(38.896595,-77.071460), //Rosslyn
          new google.maps.LatLng(38.900599,-77.050273),
          new google.maps.LatLng(38.901311,-77.03981),
          new google.maps.LatLng(38.901316,-77.033652),
          new google.maps.LatLng(38.898303,-77.028099),
          new google.maps.LatLng(38.893757,-77.028218),
          new google.maps.LatLng(38.888022,-77.028232),
          new google.maps.LatLng(38.884775,-77.021964),
          new google.maps.LatLng(38.884958,-77.01586),
          new google.maps.LatLng(38.884968,-77.005137),
          new google.maps.LatLng(38.884124,-76.995334),
          new google.maps.LatLng(38.880841,-76.985721),
          new google.maps.LatLng(38.88594,-76.977485)],
          strokeColor:"#0000CC", strokeOpacity:1, strokeWeight:3});
        blueline_rosslyn_armory.setMap(map);

        // Drawing Blue line Stadium Armory - Largo
        var blueline_armory_largo = new google.maps.Polyline({path:[
          new google.maps.LatLng(38.88594,-76.977485),
          new google.maps.LatLng(38.890488,-76.938291),
          new google.maps.LatLng(38.889757,-76.913382),
          new google.maps.LatLng(38.886713,-76.893592),
          new google.maps.LatLng(38.8913,-76.8682),
          new google.maps.LatLng(38.9008,-76.8449)], 
          strokeColor:"#0000CC", strokeOpacity:1, strokeWeight:10});
        blueline_armory_largo.setMap(map);
      
        // Drawing Yellow line Huntington - King St
        var yellowline_huntington_king = new google.maps.Polyline({path:[
          new google.maps.LatLng(38.793841,-77.075301),
          new google.maps.LatLng(38.800313,-77.071173),
          new google.maps.LatLng(38.806474,-77.061115)], 
          strokeColor:"#FFFF00", strokeOpacity:1, strokeWeight:8});
        yellowline_huntington_king.setMap(map);
      
        // Drawing Yellow line King St. - Pentagon half width
        var yellowline_king_pentagon = new google.maps.Polyline({path:[
          new google.maps.LatLng(38.806474,-77.061115),
          new google.maps.LatLng(38.814009,-77.053763),
          new google.maps.LatLng(38.852985,-77.043805),
          new google.maps.LatLng(38.85779,-77.050589),
          new google.maps.LatLng(38.863045,-77.059507),
          new google.maps.LatLng(38.869349,-77.054013)], 
          strokeColor:"#FFFF00", strokeOpacity:1, strokeWeight:3});
        yellowline_king_pentagon.setMap(map);
      
        // Drawing Yellow line Pentagon - Lenfant
        var yellowline_pentagon_lenfant = new google.maps.Polyline({path:[
          new google.maps.LatLng(38.869349,-77.05401),
          new google.maps.LatLng(38.884775,-77.021964)], 
          strokeColor:"#FFFF00", strokeOpacity:1, strokeWeight:8});
        yellowline_pentagon_lenfant.setMap(map);

        // Yellow line Lenfant - Mt Vernon half width
        // Added extension to Fort Totten effective 12/31/2006
        var yellowline_lenfant_mtvernon = new google.maps.Polyline({path:[
          new google.maps.LatLng(38.884775,-77.021964),
          new google.maps.LatLng(38.893893,-77.021902),
          new google.maps.LatLng(38.89834,-77.021851),
          new google.maps.LatLng(38.905604,-77.022256),
          new google.maps.LatLng(38.912919,-77.022194),
          new google.maps.LatLng(38.916489,-77.028938),
          new google.maps.LatLng(38.928672,-77.032775),
          new google.maps.LatLng(38.936077,-77.024728),
          new google.maps.LatLng(38.951777,-77.002174)], 
          strokeColor:"#FFFF00", strokeOpacity:1, strokeWeight:3});
        yellowline_lenfant_mtvernon.setMap(map);

        draw_station_markers(redline.getPath());
        draw_station_markers(orangeline.getPath());
        draw_station_markers(greenline.getPath());
        draw_station_markers(blueline_franconia_rosslyn.getPath());
        draw_station_markers(blueline_rosslyn_armory.getPath());
        draw_station_markers(blueline_armory_largo.getPath());
        draw_station_markers(yellowline_huntington_king.getPath());
        draw_station_markers(yellowline_king_pentagon.getPath());
        draw_station_markers(yellowline_pentagon_lenfant.getPath());
        draw_station_markers(yellowline_lenfant_mtvernon.getPath());

        AutoCenter();

        function draw_station_markers(station_path) {
          for (var i = 0; i < station_path.getLength(); i++) {
            var image = new google.maps.MarkerImage('/media/pylon.png', null, null, new google.maps.Point(4, 4));
            var markerOptions = {
              position: station_path.getAt(i),
              icon: image,
              map:map
            };

            marker = new google.maps.Marker(markerOptions);
          }
        }

        function AutoCenter() {
          var bounds = new google.maps.LatLngBounds();
          for (var url in apartments) {
            bounds.extend(apartments[url].position);
          };
          map.fitBounds(bounds);
        }
      }
    </script>
{% endblock %}

{% block title %} Welcome to By the Metro {% endblock %}

{% block content %}
    <div style="border: 1px dotted;" id="map_canvas"></div>
{% endblock %}

bythemetro/templates/table.html
{% extends "base.html" %}

{% block title %} Welcome to By the Metro {% endblock %}

{% block content %}
  {% if user.username %}
    <p>Welcome {{ user.username }}! Manage your <a href="/user/{{ user.id }}/">alerts</a></p>
  {% else %}
    <p>You need to <a href="/login/">login</a> before you can create and manage alerts</p>
  {% endif %}

  <br />

  {{ metro_system.name }}
  <ul>
  {% for station in metro_system.station_set.all %}
    <li>{{station.name}}</li>
    <ul>
    {% for apartment_near_station in station.apartmentnearstation_set.all %}
      <li>
        {{apartment_near_station.distance|floatformat}} miles
        <a target='_blank' href='{{apartment_near_station.apartment.url}}'>{{apartment_near_station.apartment.title}}</a>
      </li>
    {% endfor %}
    </ul>
  {% endfor %}
  </ul>
{% endblock %}

bythemetro/templates/user.html
{% extends "base.html" %}

{% block title %} User {{ user.username }} {% endblock %}

{% block content %}
  <table>
    <tr>
      <td style="width: 60px;">user:</td>
      <td>{{ user.username }}</td>
    </tr>
    <tr>
      <td style="width: 60px;">email:</td>
      <td>{{ user.email }}</td>
    </tr>
    <tr></tr>
    <tr>
      <td colspan="2"><a href="/password_change/">Change</a> your password.</td>
    </tr>
    <tr>
      <td colspan="2"><a href="/password_reset/">Reset</a> your password.</td>
  </table>
{% endblock %}